name: Deploy CorpAI Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'corpai-backend/**'  # Trigger workflow only when changes are made in the backend folder

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Navigate to backend directory, create virtual environment, and install dependencies
      - name: Set up virtual environment and install dependencies
        working-directory: ./corpai-backend  # Set the working directory to corpai-backend
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
          ./venv/bin/pip install zappa

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Deploy to AWS Lambda using Zappa
      - name: Deploy with Zappa
        working-directory: ./corpai-backend
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ./venv/bin/zappa deploy dev || ./venv/bin/zappa update dev

      # Step 6: Post-deployment check
      - name: Check deployment status
        working-directory: ./corpai-backend
        run: |
          ./venv/bin/zappa status dev
