name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'corpai-ui/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: corpai/corpai-ui  # Set the working directory to the Nx monorepo root

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use the Node.js version compatible with Next.js v14.1)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the Node.js version compatible with your project

      # Step 3: Cache Node.js dependencies to speed up builds
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            corpai/corpai-ui/node_modules
            corpai/corpai-ui/apps/**/node_modules
            corpai/corpai-ui/libs/**/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('corpai/corpai-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci  # Ensures clean install, uses package-lock.json for consistency

      # Step 5: Build the Next.js project (Nx build with static export)
      - name: Build project
        run: npx nx build corpai-ui --prod

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Sync static build files to S3 bucket
     
