name: Deploy CorpAI Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'corpai-backend/**'  # Trigger workflow only when changes are made in the backend folder

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Set up virtual environment, install dependencies, and deploy with Zappa
      - name: Deploy with Zappa
        working-directory: ./corpai-backend
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa
          zappa deploy dev || zappa update dev

      # Step 4: Post-deployment check
      - name: Check deployment status
        working-directory: ./corpai-backend
        run: |
          source venv/bin/activate
          zappa status dev
